### ISSUE TITLE
Links to Discord Server and Unreal Angelscript broken.

### ISSUE THREAD

**Issue by sirhelly** [Hazelight/Docs-UnrealEngine-Angelscript#7]
I came upon this page https://angelscript.hazelight.se/
and tried to follow the installation guide, but it seems that the links to the source code
and also to the discord server are broken.

**Comment by GGLucas** [comment]
Could not reproduce. Both links are valid.

**Comment by sirhelly** [comment]
Thanks for your check but I am sorry it does not work - i try to be more precise.
When trying to [https://github.com/Hazelight/UnrealEngine-Angelscript/releases](https://github.com/Hazelight/UnrealEngine-Angelscript/releases)
I get a „404 - This is not the page you are looking for“ from github.
I checked with various worldwide page status tools and got the same result.
Maybe the repo went private and is not public accessible?
